// Generated by https://quicktype.io

export interface Test {
  id: string;
  name: string;
  url: string;
  createdAt: string;
  questions?: Question[];
}

export interface Question {
  id: string;
  description: string;
  testId?: string;
  answers: Answer[];
}

export interface Answer {
  id: string;
  description: string;
  isCorrect: boolean;
}
